version: '3'
services:
  app:
    container_name: laravelkickstartapp
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - 8082:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravelkickstart
    depends_on:
      - db    

  db:
    image: mysql:5.7
    container_name: laravelkickstartdb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravelkickstartdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: krishnan
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravelkickstartdb:/var/lib/mysql
    ports:
      - 8083:3306
    networks:
      - laravelkickstart

networks:
    laravelkickstart:
        driver: bridge
volumes:
    laravelkickstartdb:
        driver: local